name = "rhythm-game-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "rhythm-game-leaderboard"
database_id = "6f83335c-6b90-4c64-8e28-fdd3dae20490"
